/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mapc;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println("zzz");
    }
}
//call au 100g dans foodtype if then else 
//le prix : pareil que cal au 100g j'invente un prix constante viande exemple 
//has unique price : vrai pr les sauces faux pour les autres
//ingredient : je mets consteucteur avec quel type + le poids
//calorie au 100g : delegué a la methode calorie au 100g  foodtype 